### PR TITLE
bazelify and use ghc 9.6.2

### PR DESCRIPTION
**Pull request by mraszyk**
This PR bazelifies the build of the Candid library for Haskell, using ghc 9.6.2.

TODO: fix the Nix build.

### CODE REVIEW

**Comment by mraszyk** [comment]
@nomeata Could you please fix the Nix build?

**Comment by nomeata** [comment]
Will you add a CI job that keeps the bazel file tested?

Alternatively, can’t you just get this library from hackage, like all the other Haskell dependencies?

**Comment by mraszyk** [comment]
> Will you add a CI job that keeps the bazel file tested?

I'm gonna give it a try!

> Alternatively, can’t you just get this library from hackage, like all the other Haskell dependencies?

I'm using [stackage](https://www.stackage.org/) and haskell-candid is not included.

**Comment by nomeata** [comment]
> I'm using [stackage](https://www.stackage.org/) and haskell-candid is not included.

`stack` certainly lets you easily add further packages from hackage, but I don’t know about bazel.

**Comment by nomeata** [comment]
@mraszyk, it seems the bazel build is broken:
```
2025/04/13 14:00:06 Downloading https://releases.bazel.build/8.1.1/release/bazel-8.1.1-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server (8.1.1) and connecting to it...
Computing main repo mapping: 
WARNING: --enable_bzlmod is set, but no MODULE.bazel file was found at the workspace root. Bazel will create an empty MODULE.bazel file. Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel. For more details, please refer to https://github.com/bazelbuild/bazel/issues/18958.
Computing main repo mapping: 
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: Target pattern parsing failed.
ERROR: Skipping ':candid': error loading package '': Unable to find package for @@[unknown repo 'rules_haskell' requested from @@]//haskell:defs.bzl: The repository '@@[unknown repo 'rules_haskell' requested from @@]' could not be resolved: No repository visible as '@rules_haskell' from main repository. Was the repository introduced in WORKSPACE? The WORKSPACE file is disabled by default in Bazel 8 (late 2024) and will be removed in Bazel 9 (late 2025), please migrate to Bzlmod. See https://bazel.build/external/migration.
ERROR: error loading package '': Unable to find package for @@[unknown repo 'rules_haskell' requested from @@]//haskell:defs.bzl: The repository '@@[unknown repo 'rules_haskell' requested from @@]' could not be resolved: No repository visible as '@rules_haskell' from main repository. Was the repository introduced in WORKSPACE? The WORKSPACE file is disabled by default in Bazel 8 (late 2024) and will be removed in Bazel 9 (late 2025), please migrate to Bzlmod. See https://bazel.build/external/migration.
INFO: Elapsed time: 6.237s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

Do you still need the bazel CI setup? If so, is there a possibility that you can update the setup?

**Comment by mraszyk** [comment]
> Do you still need the bazel CI setup?

Not really since the dfinity/ic repository [pins](https://github.com/dfinity/ic/blob/c00595a6d751190d7eaf15516e28c56d990a5ffa/MODULE.bazel#L622) the dependency and I don't expect a need to update the dependency since we're currently working replacing the Haskell test suite by Rust tests and target this work to be done within a few months from now.

Thanks for asking, @nomeata !

**Comment by nomeata** [comment]
Replacing Haskell by Rust? That's so 2018 ;-).

I removed the bazel CI build, should you need it you are welcome to revive it of course.

**Pull request merged**
